=pod

=head1 NAME

crypto-tools.git  - A small collection of crypto tools written by me

=head1 DESCRIPTION

These crypo tools have been written for my amusement, or the amusement of others. Nothing provided here will result in any real security.

=head2 spdxor.pl

This is a simple tool to xor the contents of a binary file with an ascii string.

=head3 Options

-i <file>  The input file

-o <file>  The output string

-s string  The Ascii string

=head2 cypherplay.pl

A simple substitution cypher that I thought would be fun to play with.

=head3 Options

-s <string>        String to encode

-d                 Decode flag.  Encode if not set

=cut
